### GET request to example server
GET http://127.0.0.1:3000/?generated-in=CLion


###

### post request to example server
POST http://127.0.0.1:3000/?generated-in=CLion
Content-Type: application/json
User-aaa: 123

{
    "name": "John",
    "age": "30"
}

###


### GET request to example server
GET http://127.0.0.1:3000/?generated-in=CLion
Content-Type: application/json
authorization: 11223